USE CookingMasterDB

GO

DELETE FROM [CookingMasterDB].[dbo].[Ingredients];

GO

DELETE FROM [CookingMasterDB].[dbo].[IngredientCategories];

GO

DBCC CHECKIDENT ('dbo.IngredientCategories', RESEED, 0);

GO

INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('All Ingredients', 'allingredients', GETDATE(), 'All Ingredients-20230822194117')
INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Fruit', 'fruit', GETDATE(), 'Fruit-20230822194117')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Vegetables', 'vegetables', GETDATE(), 'Vegetables-20230822194136')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Spices', 'spices', GETDATE(), 'Spices-20230822194144')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Meat', 'meat', GETDATE(), 'Meat-20230822194155')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Seafood', 'seafood', GETDATE(), 'Seafood-20230822194204')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Cereals', 'cereals', GETDATE(), 'Cereals-20230822194215')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Dairy Product', 'dairyproduct', GETDATE(), 'Dairy Product-20230822194117')
  INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Nuts', 'nuts', GETDATE(), 'Nuts-20230822194117')
 INSERT INTO IngredientCategories (CategoryName, IconPath, CreateDate, Uid)
 VALUES ('Other', 'other', GETDATE(), 'Other-20230822194117')

GO

DBCC CHECKIDENT ('dbo.Ingredients', RESEED, 0);

GO

INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'banana', GETDATE(), 'Banana-20230822194215', 'Banana')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'blackberry', GETDATE(), 'Blackberry-20230832194215', 'Blackberry')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'bluegrape', GETDATE(), 'Blue Grape-20230821194215', 'Blue Grape')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'greenapple', GETDATE(), 'Green Apple-20230825194215', 'Green Apple')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'kiwi', GETDATE(), 'Kiwi-20230822194215', 'Kiwi')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'orange', GETDATE(), 'Orange-20220822194215', 'Orange')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'cherry', GETDATE(), 'Cherry-24230822194215', 'Cherry')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'lemon', GETDATE(), 'Lemon-20230822194215', 'Lemon')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'lime', GETDATE(), 'Lime-20230822194215', 'Lime')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'peach', GETDATE(), 'Peach-20230882194215', 'Peach')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'pear', GETDATE(), 'Pear-20237822194215', 'Pear')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'pineapple', GETDATE(), 'Pineapple-20237822194215', 'Pineapple')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'raspberry', GETDATE(), 'Raspberry-20237822194215', 'Raspberry')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'redapple', GETDATE(), 'Red Apple-20237822194215', 'Red Apple')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (2, 'strawberries', GETDATE(), 'Strawberries-20237822194215', 'Strawberries')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'carrot', GETDATE(), 'Carrot-20237822194215', 'Carrot')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'cabbage', GETDATE(), 'Cabbage-20237822194215', 'Cabbage')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'asparagus', GETDATE(), 'Asparagus-20237822194215', 'Asparagus')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'blackolive', GETDATE(), 'Black Olive-20237822194215', 'Black Olive')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'broccoli', GETDATE(), 'Broccoli-20237822194215', 'Broccoli')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'celeriac', GETDATE(), 'Celeriac-20237822194215', 'Celeriac')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'garlic', GETDATE(), 'Garlic-20237822194215', 'Garlic')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'potato', GETDATE(), 'Potato-20237822194215', 'Potato')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'onion', GETDATE(), 'Onion-20237822194215', 'onion')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'redchillipepper', GETDATE(), 'Red Chilli Pepper-20237822194215', 'Red Chilli Pepper')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'peas', GETDATE(), 'Peas-20237822194215', 'Peas')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (3, 'pumpkin', GETDATE(), 'Pumpkin-20237822194215', 'Pumpkin')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (4, 'basil', GETDATE(), 'Basil-20237822194215', 'Basil')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (4, 'oregano', GETDATE(), 'Oregano-20237822194215', 'Oregano')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (4, 'salt', GETDATE(), 'Salt-20237822194215', 'Salt')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (4, 'sugar', GETDATE(), 'Sugar-20237822194215', 'Sugar')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (5, 'bacon', GETDATE(), 'Bacon-20237822194215', 'Bacon')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (5, 'beefsteak', GETDATE(), 'Beef Steak-20237822194215', 'Beef Steak')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (5, 'salami', GETDATE(), 'Salami-20237822194215', 'Salami')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (5, 'sausage', GETDATE(), 'Sausage-20237822194215', 'Sausage')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (6, 'cannedtuna', GETDATE(), 'Canned Tuna-20237822194215', 'Canned Tuna')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (6, 'salmon', GETDATE(), 'Salmon-20237822194215', 'Salmon')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (6, 'tilapia', GETDATE(), 'Tilapia-20237822194215', 'Tilapia')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (8, 'milk', GETDATE(), 'Milk-20237822194215', 'Milk')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (8, 'yogurt', GETDATE(), 'Yogurt-20237822194215', 'Yogurt')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (8, 'cheese', GETDATE(), 'Cheese-20237822194215', 'Cheese')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (10, 'oliveoil', GETDATE(), 'Olive Oil-20237822194215', 'Olive Oil')
INSERT INTO Ingredients (CategoryId, IconPath, CreateDate, Uid, IngredientName)
VALUES (10, 'honey', GETDATE(), 'Honey-20237822194215', 'Honey')

